### ISSUE TITLE
upper/lowercase slide name

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/pytaVSL#1]
Si un slide est chargé depuis un fichier avec une majuscule, le nom du slide contient la majuscule. Les messages osc adressés doivent lui être adressés avec cette majuscule.
De son côté, le système de sauvegarde de scènes redescend la casse de tous les noms vers des minuscules.
Lorsqu'on charge une scène, tout se passe bien dans pyta, mais tout contrôle extérieur (mentat, par exemple) est rompu.

**Comment by jean-emmanuel** [comment]
C'est chelou, normalement tout est passé en lowercase dans pyta justement, les noms des slides, et les adresses osc entrante pour éviter ce  genre de problème justement.

**Comment by jean-emmanuel** [comment]
Je confirme, ici le nom du slide ne contient pas de majuscules quand on le charge même si le fichier en contient et les messages de contrôle fonctionnent quelle que soit la casse.
